carCommerce_project/carCommerce/urls.py
from django.contrib import admin
from django.urls import path
import carComm_app.views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', carComm_app.views.home, name = 'home'),
    path('', carComm_app.views.home, name = 'home'),
    path('listings/', carComm_app.views.listings, name = 'listings'),
    path('contact/', carComm_app.views.contact, name = 'contact'),
    path('carDetails/<str:registration>/', carComm_app.views.carDetails, name ='carDetails'),
    path('purchaseForm/<str:registration>/', carComm_app.views.purchaseForm, name = 'purchaseForm')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

carCommerce_project/carComm_app/models.py
import datetime
from unittest.util import _MAX_LENGTH
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

currentDate = datetime.date.today()
currentYear = currentDate.year

class Listing(models.Model):
    make = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    registration = models.CharField(max_length=10)
    colour = models.CharField(max_length=50)
    year = models.IntegerField(validators=[MaxValueValidator(currentYear), MinValueValidator(1769)])
    mileage = models.IntegerField(validators=[MinValueValidator(1)])
    thumbnail = models.ImageField(upload_to='images/')
    description = models.TextField(max_length=2500)
    price = models.FloatField(validators=[MinValueValidator(0.01)])
    pending_sale = models.BooleanField(default=False)
    
    def __str__(self) -> str:
        return self.make + " " + self.model + ", " + self.registration

    def getColour(self) -> str:
        return self.colour

class ListingImage(models.Model):
    image = models.ImageField(upload_to='images/')
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.listing.make + " " + self.listing.model + ", " + self.listing.registration

class Queries(models.Model):
    def uniqueColours() -> list:
        uniqueColours = Listing.objects.all().order_by('colour').values_list('colour', flat=True).distinct()

        return uniqueColours

    def uniqueMakes() -> list:
        uniqueMakes = Listing.objects.all().order_by('make').values_list('make', flat=True).distinct()
        
        return uniqueMakes

carCommerce_project/carComm_app/forms.py
from django import forms
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox
from phonenumber_field.formfields import PhoneNumberField

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email_address = forms.EmailField(max_length=100)
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea, max_length=1000)
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox, label="")

class PurchaseForm(forms.Form):
    name = forms.CharField(max_length=100)
    email_address = forms.EmailField(max_length=100)
    phone = PhoneNumberField(label="Contact number")
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox, label="")

carCommerce_project/carComm_app/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponse
from django.core.mail import send_mail, BadHeaderError
from .forms import ContactForm, PurchaseForm
from .models import Listing, ListingImage, Queries
from .filters import ListingFilter

def home(request):
    listings = Listing.objects.all()
    return render(request, 'home.html', {'listings':listings})

def listings(request):
    uniqueColours = Queries.uniqueColours()
    uniqueMakes = Queries.uniqueMakes()
    listings = Listing.objects.all()
    listingFilter = ListingFilter(request.GET, queryset=listings)
    return render(request, 'listings.html', {'listings':listings, 'uniqueColours':uniqueColours, 'uniqueMakes':uniqueMakes, 'listingFilter': listingFilter})

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            body = {
            'name': form.cleaned_data['name'],
            'email': form.cleaned_data['email_address'],
            'subject': form.cleaned_data['subject'],
            'message':form.cleaned_data['message'],
            }
            message = "\n".join(body.values())
            email = form.cleaned_data['email_address']
            confirmation = "Thank you! Your email has been submitted and you should hear back from us within 2 working days."
            try:
                send_mail("Web enquiry", message, email, ['enquiries@carcommerce.uk'])
                newForm = ContactForm()
                return render(request, 'contact.html', {'contactForm': newForm, 'confirmation': confirmation})
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
        else:
            confirmation = "Sorry, we were unable to submit this email. Did you complete the reCAPTCHA above?"
            return render(request, 'contact.html', {'contactForm': form, 'confirmation': confirmation})
    else:
        form = ContactForm()
    return render(request, 'contact.html', {'contactForm': form})

def purchaseForm(request, registration):
    try:
        listing = Listing.objects.get(registration=registration)
    except Listing.DoesNotExist:
        raise Http404("Car with registration \"" + registration + "\" not found")
    
    if request.method == 'POST':
        form = PurchaseForm(request.POST)
        if form.is_valid():
            body = {
            'car': listing.__str__(),
            'name': form.cleaned_data['name'],
            'email': form.cleaned_data['email_address'],
            'phone': form.cleaned_data['phone'].__str__(),
            }
            message = "\n".join(body.values())
            email = form.cleaned_data['email_address'],
            confirmation = "Thank you! Your purchase request has been sent. We will mark the " + listing.make + " " + listing.model + " as 'sold pending payment' and call within 2 working days to arrange payment and collection."
            try:
                send_mail("Purchase enquiry", message, email, ['sales@carcommerce.uk'])
                newForm = PurchaseForm
                return render(request, 'purchaseForm.html', {'purchaseForm': newForm, 'confirmation': confirmation})
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
        else:
            confirmation = "Sorry, we were unable to submit this purchase request. Did you complete the reCAPTCHA above?"
            return render(request, 'purchaseForm.html', {'purchaseForm': form, 'confirmation': confirmation})
    else:
        form = PurchaseForm()
    return render(request, 'purchaseForm.html', {'purchaseForm': form, 'listing': listing})
        

def carDetails(request, registration):
    try:
        listing = Listing.objects.get(registration=registration)
        listingImages = ListingImage.objects.filter(listing_id=listing.id)
    except Listing.DoesNotExist:
        raise Http404("Car with registration \"" + registration + "\" not found")

    return render(request, 'carDetails.html', {'listing': listing, 'listingImages': listingImages})

carCommerce_project/carComm_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %}{% endblock title %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static "assets/img/favicon.png" %}" rel="icon">
  <link href="{% static "assets/img/apple-touch-icon.png" %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700|Raleway:300,400,400i,500,500i,700,800,900" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static "assets/vendor/animate.css/animate.min.css" %}" rel="stylesheet">
  <link href="{% static "assets/vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "assets/vendor/bootstrap-icons/bootstrap-icons.css" %}" rel="stylesheet">
  <link href="{% static "assets/vendor/boxicons/css/boxicons.min.css" %}" rel="stylesheet">
  <link href="{% static "assets/vendor/glightbox/css/glightbox.min.css" %}" rel="stylesheet">
  <link href="{% static "assets/vendor/swiper/swiper-bundle.min.css" %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static "assets/css/style.css" %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: eBusiness - v4.9.1
  * Template URL: https://bootstrapmade.com/ebusiness-bootstrap-corporate-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<!-- ======= Header ======= -->
<header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex justify-content-between">

      <div class="logo">
        <h1><a href="{% url 'home' %}"><span>Car</span>Commerce<span><i class="bi bi-car-front"></i></span></a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="{% static "assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          {% block navbar %}
          {% endblock navbar %}
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

<body>
    {% block content %}{% endblock content %}
</body>

  <!-- ======= Footer ======= -->
  <footer>
    <div class="footer-area">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <div class="footer-content">
              <div class="footer-head">
                <div class="footer-logo">
                  <h2><span>Car</span>Commerce<span><i class="bi bi-car-front"></i></span></h2>
                </div>

                <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis.</p>
                <div class="footer-icons">
                </div>
              </div>
            </div>
          </div>
          <!-- end single footer -->
          <div class="col-md-4">
            <div class="footer-content">
              <div class="footer-head">
                <div class="flicker-img">
                  <!-- left blank to separate footer content -->
                </div>
              </div>
            </div>
          </div>
          <!-- end single footer -->
          <div class="col-md-4">
            <div class="footer-content">
              <div class="footer-head">
                <h4>information</h4>
                <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.
                </p>
                <div class="footer-contacts">
                  <p><span>Tel:</span> +123 456 789</p>
                  <p><span>Email:</span> enquiries@carcommerce.uk</p>
                  <p><span>Working Hours:</span> 9am-5pm</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="footer-area-bottom">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="copyright text-center">
              <p>
                &copy; Copyright <strong>CarCommerce</strong>. All Rights Reserved
              </p>
            </div>
            <div class="credits">
              Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>, adapted by ARU Student
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer><!-- End  Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="{% static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
  <script src="{% static "assets/vendor/glightbox/js/glightbox.min.js" %}"></script>
  <script src="{% static "assets/vendor/isotope-layout/isotope.pkgd.min.js" %}"></script>
  <script src="{% static "assets/vendor/swiper/swiper-bundle.min.js" %}"></script>
  <script src="{% static "assets/vendor/php-email-form/validate.js" %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static "assets/js/main.js" %}"></script>

</body>

</html>

carCommerce_project/carComm_app/templates/carDetails.html
{% extends 'base.html' %}
{% load humanize %}

{% block navbar %}
<li><a href="{% url 'home' %}">Home</a></li>
<li><a href="{% url 'listings' %}">View all cars</a></li>
<li><a href="{% url 'contact' %}">Contact</a></li>
{% endblock navbar %}

{% block content %}

<style>
  .carousel-item{
    object-fit:contain;
    max-height:100%;
    object-position: center;
  }
  #hero {
    height: 40vw !important;
    max-height: 766px !important;
  }
</style>

<main id="main" style="width: 80%;margin-left:10%;padding-top:90px;" >
    <div class="container" style="padding-bottom:50px;">
        <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <div class="section-headline services-head text-center">
                    <h2>{{listing.year}} {{listing.make}} {{listing.model}}</h2>
                  </div>
                </div>
            <!-- Carousel -->
            <section id="hero" style="height:45vw">
              <div class="hero-container">
                <div id="heroCarousel" class="carousel slide carousel-fade" data-bs-ride="carousel" data-bs-interval="10000">
          
                  <ol id="hero-carousel-indicators" class="carousel-indicators"></ol>
          
                  <div class="carousel-inner" role="listbox">
          
                    <a href="{{listing.thumbnail.url}}"><img class="carousel-item active" src="{{listing.thumbnail.url}}"></a>
                    
                    {% for image in listingImages%}
                    <a href ={{image.image.url}}><img class="carousel-item" src="{{image.image.url}}"></a>
                    {% endfor %}

                  </div>
          
                  <a class="carousel-control-prev" href="#heroCarousel" role="button" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon bi bi-chevron-left" aria-hidden="true"></span>
                  </a>
          
                  <a class="carousel-control-next" href="#heroCarousel" role="button" data-bs-slide="next">
                    <span class="carousel-control-next-icon bi bi-chevron-right" aria-hidden="true"></span>
                  </a>
          
                </div>
              </div>
            </section><!-- End Carousel section -->
            
            <h4>£{{listing.price|floatformat:2|intcomma}}</h4>
            <h4><b>Colour:</b> {{listing.colour|capfirst}}</h4>
            <h4><b>Mileage:</b> {{listing.mileage|intcomma}} miles</h4>
            <h4><b>Description:</b></h4>
            <p>{{listing.description}}</p>
            {% if listing.pending_sale == False %}
              <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'purchaseForm' listing.registration %}" style="font-size:20pt;margin-top:25px!important;">Purchase</a></div>
            {% else %}
              <h3 style="color:rgb(172, 0, 0);width:100%;text-align:center;">Sold, pending payment</h3>
              <h4 style="color:rgb(172, 0, 0);width:100%;text-align:center;">In the unlikely event that for whatever reason this sale doesn't go through, this car may become available again.<br>To avoid disappointment, we recommend treating it as sold for now.</h4>
            {% endif %}
        </div>
    </div>

</main>

{% endblock content %}

carCommerce_project/carComm_app/templates/contact.html
{% extends 'base.html' %}

{% block navbar %}
<li><a href="{% url 'home' %}">Home</a></li>
<li><a href="{% url 'listings' %}">View all cars</a></li>
<li><a class="nav-link scrollto active" href="{% url 'contact' %}">Contact</a></li>
{% endblock navbar %}

{% block content %}

<style>
  #id_name, #id_email_address, #id_subject, #id_message {
    width: 100%;
    background-color: rgb(245, 245, 245);
  }
  button {
    width:20%;
    margin-left:40%;
  }
  #id_captcha.g-recaptcha {
    width:304px;
    margin-left: auto;
    margin-right: auto;
  }
</style>


<!-- ======= Contact Section ======= -->
<div id="contact" class="contact-area">
    <div class="contact-inner area-padding">
      <div class="contact-overly"></div>
      <div class="container ">
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="section-headline text-center">
              <br><br><h2>Contact Us</h2><br><br>
            </div>
          </div>
        </div>
        <div class="row">
          <!-- Start contact icon column -->
          <div class="col-md-4">
            <div class="contact-icon text-center">
              <div class="single-icon">
                <i class="bi bi-phone"></i>
                <p>
                  Call: +1 5589 55488 55<br>
                  <span>Monday-Friday (9am-5pm)</span>
                </p>
              </div>
            </div>
          </div>
          <!-- Start contact icon column -->
          <div class="col-md-4">
            <div class="contact-icon text-center">
              <div class="single-icon">
                <i class="bi bi-envelope"></i>
                <p>
                  Email: enquiries@carcommerce.uk<br>
                </p>
              </div>
            </div>
          </div>
          <!-- Start contact icon column -->
          <div class="col-md-4">
            <div class="contact-icon text-center">
              <div class="single-icon">
                <i class="bi bi-geo-alt"></i>
                <p>
                  Location: 123 Non-existent Street<br>
                  <span>King's Lynn, Norfolk</span>
                </p>
              </div>
            </div>
          </div>
        </div>
        <div class="row">

          <!-- Start Google Map -->
          <div class="col-md-6">
            <!-- Start Map -->
            <iframe src="https://maps.google.com/maps?q=king's%20lynn&amp;t=&amp;z=16&amp;ie=UTF8&amp;iwloc=&amp;output=embed" id="gmap_canvas" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
            <!-- End Map -->
          </div>
          <!-- End Google Map -->

          <!-- Start contact -->
          <div class="col-md-6">
            <form method="POST" style="width:100%;">
              {% csrf_token %}
              {{contactForm.as_p}}
              <button type="submit" id="id_submit">Submit</button>
              <p><br><b>{{confirmation}}</b></p>
            </form>
          </div>

          
        </div>
      </div>
    </div>
  </div><!-- End Contact Section -->
  
  <script async src="https://www.google.com/recaptcha/api.js"></script>

  {% endblock content %}

carCommerce_project/carComm_app/templates/home.html
{% extends 'base.html' %} 

{% load static %}
{% load mathfilters %}
{% load humanize %}

{% block title %}carCommerce - Home{% endblock title %} 

{% block navbar %}
<li><a class="nav-link scrollto active" href="{% url 'home' %}">Home</a></li>
<li><a class="nav-link scrollto" href="#about">Recently added</a></li>
<li><a href="{% url 'listings' %}">View all cars</a></li>
<li><a class="nav-link scrollto" href="#services">About us</a></li>
<li><a href="{% url 'contact' %}">Contact</a></li>
{% endblock navbar %}

{% block content %}

  <style>
    #hero .carousel-item::before {
  content: "";
  background-color: rgba(0, 0, 0, 0.7);
  }
  </style>

  <!-- ======= Carousel section ======= -->
  <section id="hero">
    <div class="hero-container">
      <div id="heroCarousel" class="carousel slide carousel-fade" data-bs-ride="carousel" data-bs-interval="5000">

        <ol id="hero-carousel-indicators" class="carousel-indicators"></ol>

        <div class="carousel-inner" role="listbox">

          <div class="carousel-item active" style="background-image: url({% static 'assets/img/carousel/carousel1.png' %});">
            <div class="carousel-container">
              <div class="container">
                <h2 class="animate__animated animate__fadeInDown">Quality second-hand cars</h2>
                <p class="animate__animated animate__fadeInUp">All our cars are fully inspected before listing, and come with a 1-year warranty</p>
                <a href="#about" class="btn-get-started scrollto animate__animated animate__fadeInUp">View recently added</a>
                <a href="{% url 'listings' %}" class="btn-get-started scrollto animate__animated animate__fadeInUp">View all cars</a>
              </div>
            </div>
          </div>

          <div class="carousel-item" style="background-image: url({% static 'assets/img/carousel/carousel2.png' %});">
            <div class="carousel-container">
              <div class="container">
                <h2 class="animate__animated animate__fadeInDown">Fantastic choice</h2>
                <p class="animate__animated animate__fadeInUp">We stock a wide variety of cars, from classics to the almost-new</p>
                <a href="#about" class="btn-get-started scrollto animate__animated animate__fadeInUp">View recently added</a>
                <a href="{% url 'listings' %}" class="btn-get-started scrollto animate__animated animate__fadeInUp">View all cars</a>
              </div>
            </div>
          </div>

          <div class="carousel-item" style="background-image: url({% static 'assets/img/carousel/carousel3.png' %});">
            <div class="carousel-container">
              <div class="container">
                <h2 class="animate__animated animate__fadeInDown">Helping you save <i class="bi bi-piggy-bank-fill"></i></h2>
                <p class="animate__animated animate__fadeInUp">All our cars are competitively priced, considering their great condition</p>
                <a href="#about" class="btn-get-started scrollto animate__animated animate__fadeInUp">View recently added</a>
                <a href="{% url 'listings' %}" class="btn-get-started scrollto animate__animated animate__fadeInUp">View all cars</a>
              </div>
            </div>
          </div>

        </div>

        <a class="carousel-control-prev" href="#heroCarousel" role="button" data-bs-slide="prev">
          <span class="carousel-control-prev-icon bi bi-chevron-left" aria-hidden="true"></span>
        </a>

        <a class="carousel-control-next" href="#heroCarousel" role="button" data-bs-slide="next">
          <span class="carousel-control-next-icon bi bi-chevron-right" aria-hidden="true"></span>
        </a>

      </div>
    </div>
  </section><!-- End Carousel section -->

  <main id="main">

    <!-- ======= Recent car listings section ======= -->
    <div id="about" class="about-area area-padding">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="section-headline text-center">
              <h2>Recently Added</h2>
            </div>
          </div>
        </div>
        <div class="row">
          <!-- Recent car listings-->
          {% with start=listings|length|sub:4|stringformat:"s" %}
            {% with end=listings|length|stringformat:"s" %}
              {% with listslice=start|add:":"|add:end %}
                {% for listing in listings|slice:listslice reversed %}
                  <div class="col mb-5">
                    <div class="card h-100">
                      <!-- Product image-->
                      <img class="card-img-top" src="{{listing.thumbnail.url}}" alt="Car thumbnail" />
                      <!-- Product details-->
                      <div class="card-body p-4">
                        <div class="text-center">
                          <!-- Product name -->
                          <h5 class="fw-bolder">{{listing.make|capfirst}} {{listing.model|capfirst}}</h5>
                          {% if listing.pending_sale == True %}
                            <h5 style="color:rgb(172, 0, 0);">Sold, pending payment</h5>
                          {% else %}
                            <!-- Product price -->  
                            £{{listing.price|floatformat:2|intcomma}}<br>
                            <!-- Product age -->
                            Year: {{listing.year}}<br>
                            <!-- Product mileage -->
                            Mileage: {{listing.mileage|intcomma}} miles
                          {% endif %}
                        </div>
                      </div>
                      <!-- Product actions-->
                      <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">                                    
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'carDetails' listing.registration %}">View details</a></div><br>
                        </div>
                      </div>
                    </div>
                {% endfor %}
              {% endwith %}
            {% endwith %}
          {% endwith %}
        <!-- End car listings-->
        </div>
        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'listings' %}" style="font-size:20pt;">View all cars</a></div><br>
      </div>
    </div>

    <!-- ======= About Us section ======= -->
    <div id="services" class="services-area area-padding" style="padding-bottom: 0;">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="section-headline services-head text-center">
              <h2>About us</h2>
            </div>
          </div>
        </div>
        <div class="row text-center">
          <!-- Start Left services -->
          <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="about-move">
              <div class="services-details">
                <div class="single-services">
                  <a class="services-icon">
                    <i class="bi bi-wrench-adjustable"></i>
                  </a>
                  <h4>Expert mechanics</h4>
                  <p>
                    Our team give each car a full inspection prior to listing. We won't sell any car that doesn't qualify for our 1-year warranty. That's the CarCommerce guarantee!
                  </p>
                </div>
              </div>
              <!-- end about-details -->
            </div>
          </div>
          <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="about-move">
              <div class="services-details">
                <div class="single-services">
                  <a class="services-icon">
                    <i class="bi bi-emoji-smile-fill"></i>
                  </a>
                  <h4>Friendly sales team</h4>
                  <p>
                    Visit us in-store to benefit from our award-winning customer service. Alternatively, you can speak to the same team via email or over the phone. See our <a href="{% url 'contact' %}">Contact page</a> for more details.
                  </p>
                </div>
              </div>
              <!-- end about-details -->
            </div>
          </div>
          <div class="col-md-4 col-sm-4 col-xs-12">
            <!-- end col-md-4 -->
            <div class=" about-move">
              <div class="services-details">
                <div class="single-services">
                  <a class="services-icon">
                    <i class="bi bi-search-heart-fill"></i>
                  </a>
                  <h4>Astounding choice</h4>
                  <p>
                    From MINI to Rolls-Royce. From budget to luxury.<br>Our amazing selection makes it incredibly easy to find a car you'll love, whatever you're looking for.
                  </p>
                </div>
              </div>
              <!-- end about-details -->
            </div>
          </div>
        </div>
      </div>
      <img src="{% static 'assets/img/about1.png' %}" class="img-fluid" alt="About section photo" style="width:100%;margin-top:50px;"/>
    </div><!-- End About Us Section -->
    
    

  </main><!-- End #main -->

 {% endblock content %}

carCommerce_project/carComm_app/templates/purchaseForm.html
{% extends 'base.html' %}

{% block navbar %}
<li><a href="{% url 'home' %}">Home</a></li>
<li><a href="{% url 'listings' %}">View all cars</a></li>
<li><a href="{% url 'contact' %}">Contact</a></li>
{% endblock navbar %}

{% block content %}

<style>
    form {
        padding-left: 15vw;
        padding-right: 15vw;
        margin-top: 5vh;
    }
    input {
        width: 100%;
    }
    #id_captcha.g-recaptcha {
    width:304px;
    margin-left: auto;
    margin-right: auto;
  }
  button {
    width:20%;
    margin-left:40%;
  }
</style>

<div class="col-md-6" style="height:70%;width:80%;margin-left:10%;margin-top:150px;">

    <h1 style="text-align:center;">Purchase {{listing.make}} {{listing.model}}</h1>
    <h3 style="text-align:center;">Please enter your details below to have this car reserved</h3>

    <form method="POST">
        {% csrf_token %}
        {{purchaseForm.as_p}}
        <button type="submit" id="id_submit">Submit</button>
        <p style="text-align:center;"><br><b>{{confirmation}}</b></p>
    </form>

</div>

{% endblock content %}